name: Gravity Bridge Binary
on: [push, pull_request]

jobs:
  amd64:
    name: Gravity Bridge Binary
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/config'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push blockchain
        run: docker buildx build --tag leeway321/gravity-bridge-binary:0.0.1 --file deploy/gravity-bridge-binary/Dockerfile --platform linux/amd64 --cache-from leeway321/gravity-bridge-binary:cache --cache-to leeway321/gravity-bridge-binary:cache --push --progress tty .
